service: big-mouth
app: big-mouth-dev
tenant: nuatu
plugins:
  - serverless-pseudo-parameters
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:scan
      Resource: 'arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/restaurants'
    - Effect: Allow
      Action: execute-api:Invoke
      Resource: 'arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:*/*/GET/restaurants'
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:PutItem
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
        - dynamodb:BatchGetItem
      Resource:
        Fn::GetAtt:
          - restaurantsTable
          - Arn
functions:
  get-index:
    handler: functions/get-index.handler
    events:
      - http:
          path: /
          method: get
    environment:
      restaurants_api: https://tcipt8vpc1.execute-api.us-east-1.amazonaws.com/dev/restaurants
      cognito_user_pool_id: us-east-1_e1vVtAD6r
      cognito_client_id: 6eugosdpmt7pa214c0ne6ta0k4
      TABLE_NAME:
        Ref: restaurantsTable
      TABLE_ARN:
        Fn::GetAtt:
          - restaurantsTable
          - Arn
  get-restaurants:
    handler: functions/get-restaurants.handler
    events:
      - http:
          path: /restaurants/
          method: get
          authorizer: aws_iam
    environment:
      restaurants_table: restaurants
      TABLE_NAME:
        Ref: restaurantsTable
      TABLE_ARN:
        Fn::GetAtt:
          - restaurantsTable
          - Arn
  search-restaurants:
    handler: functions/search-restaurants.handler
    events:
      - http:
          path: /restaurants/search
          method: post
          authorizer:
            arn: arn:aws:cognito-idp:us-east-1:572031701257:userpool/us-east-1_e1vVtAD6r
    environment:
      restaurants_table: restaurants
      TABLE_NAME:
        Ref: restaurantsTable
      TABLE_ARN:
        Fn::GetAtt:
          - restaurantsTable
          - Arn
resources:
  Resources:
    restaurantsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restaurants
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: name
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1